django_htmx/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include(('expensetracker.urls', 'expensetracker'), namespace='expensetracker')),
    path('bruh/', admin.site.urls),
]

expensetracker/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('expense', views.add_expense, name='add_expense'),
    path('expenses', views.get_expenses, name='get_expenses'),
    path('about', views.about, name='about')
]

expensetracker/models.py
import django.utils.timezone
from django.db import models
from django.utils.timezone import now


# Create your models here.

class ExpenseItem(models.Model):
    expense_item_id = models.BigAutoField(primary_key=True)
    item_name = models.CharField(max_length=500)
    item_price = models.FloatField()
    date = models.DateTimeField(default=django.utils.timezone.now)

expensetracker/views.py
from django import forms
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST, require_GET

from expensetracker.models import ExpenseItem


# Create your views here.

class ExpenseItemForm(forms.Form):
    item_name = forms.CharField(required=True)
    item_price = forms.FloatField(required=True, min_value=1)


def index(request):
    return render(request, 'expensetracker/index.html')


def get_expenses(request):
    expenses = ExpenseItem.objects.all()
    expenses_html = []
    for expense in expenses:
        expenses_html.append(render_to_string('components/card.html', context={'expense_data': expense}))
    return HttpResponse("\n".join(expenses_html))


@require_POST
def add_expense(request):
    data = ExpenseItemForm(request.POST)
    if data.is_valid():
        expense_item = ExpenseItem()
        expense_item.item_name = data.cleaned_data['item_name']
        expense_item.item_price = data.cleaned_data['item_price']
        expense_item.save()

        context = {
            'expense_data': expense_item
        }
        return render(request, 'components/card.html', context=context)
    else:
        return render(request, data)


@require_GET
def expenses_chart(request):
    return render(request, 'expensetracker/chart.html')


@require_GET
def about(request):
    return render(request, 'expensetracker/about.html')

templates/common/_base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://unpkg.com/htmx.org@1.9.4"></script>
    <script src="{% static 'lib/preline/dist/preline.js' %}" defer></script>
    {% block inlinescripts %} {% endblock %}
    {% block title %}
        <title>Django+HTMX</title>
    {% endblock %}
    <link href="{% static 'css/output.css' %}" rel="stylesheet">
</head>
<body>
{% include "common/_navbar.html" %}
{% block content %}
{% endblock %}
</body>
</html>

templates/common/_navbar.html
<div>
    <ul class="flex flex-row gap-5">
        <li class="block">
            <a href="{% url 'expensetracker:index' %}">Expenses list</a>
        </li>
        <li class="block">
            <a href="{% url 'expensetracker:about' %}">About</a>
        </li>
    </ul>
</div>

templates/components/card.html
<div>
    Name: {{ expense_data.item_name }}
    Price: {{ expense_data.item_price }}
    Date: {{ expense_data.date|date:"M. d, Y" }}
</div>

templates/components/test.html
<div>
    Name: {{ expense_data.item_name }}
    Price: {{ expense_data.item_price }}
</div>

templates/expensetracker/about.html
{% include "common/_base.html" %}
<p>Full-stack web app built using HTMX and Django</p>

templates/expensetracker/chart.html
<h3>Charts should go here</h3>

templates/expensetracker/index.html
{% extends "common/_base.html" %}

{% block title %}
    <title>ExpenseTracker</title>
{% endblock %}
{% block content %}
    <h2 class="text-3xl">Add expense:</h2>
    <form hx-post="/expense" hx-swap="beforeend" hx-target="#expenses_list">
        {% csrf_token %}
        <label for="item_name">Item name:</label>
        <input id="item_name" type="text" placeholder="Expense name" name="item_name"/>

        <label for="item_price">Item price:</label>
        <input id="item_price" type="number" placeholder="100" required name="item_price"/>

        <button type="submit">Add expense</button>
    </form>
    {% include "expensetracker/chart.html" %}
    <h1>List of expenses:</h1>
    <div id="expenses_list" hx-get="/expenses" hx-trigger="load">

    </div>
{% endblock %}